/* ============================================================
   TRACEGRAD LANDING PAGE NAVIGATION
   ============================================================ */

const LSEC_DISPLAY = {
  home: 'flex',
  about: 'block',
  gallery: 'block',
  devs: 'block'
};

const LNK_MAP = {
  home: 'lnk-home',
  about: 'lnk-about',
  gallery: 'lnk-gallery',
  devs: 'lnk-devs'
};

function showSection(id, btn, updateHash = true) {
  const target = document.getElementById('lsec-' + id);

  if (!target) return;

  // Hide all sections
  document.querySelectorAll('.lsec').forEach(function(sec) {
    sec.classList.remove('on');
    sec.style.display = 'none';
  });

  // Show selected section
  target.classList.add('on');
  target.style.display = LSEC_DISPLAY[id] || 'block';

  // Update navigation active state
  document.querySelectorAll('.lnav-link').forEach(function(link) {
    link.classList.remove('on');
  });

  const activeLink =
    btn || document.getElementById(LNK_MAP[id]);

  if (activeLink) {
    activeLink.classList.add('on');
  }

  // Update URL hash
  if (updateHash && window.history && history.pushState) {
    history.pushState(
      { section: id },
      '',
      '#' + id
    );
  }

  // Scroll to top
  window.scrollTo({
    top: 0,
    left: 0,
    behavior: 'smooth'
  });
}


/* ============================================================
   BROWSER BACK / FORWARD SUPPORT
   ============================================================ */

window.addEventListener('popstate', function() {
  const id = window.location.hash
    .replace('#', '')
    .toLowerCase();

  const valid = [
    'home',
    'about',
    'gallery',
    'devs'
  ];

  showSection(
    valid.includes(id) ? id : 'home',
    null,
    false
  );
});


/* ============================================================
   INITIAL PAGE LOAD
   ============================================================ */

document.addEventListener('DOMContentLoaded', function() {
  const id = window.location.hash
    .replace('#', '')
    .toLowerCase();

  const valid = [
    'home',
    'about',
    'gallery',
    'devs'
  ];

  showSection(
    valid.includes(id) ? id : 'home',
    null,
    false
  );
});


/* ============================================================
   BACK TO TOP
   ============================================================ */

window.addEventListener('scroll', function() {
  const backToTop = document.getElementById('back-to-top');

  if (!backToTop) return;

  backToTop.classList.toggle(
    'show',
    window.scrollY > 420
  );
});


/* ============================================================
   TRACEGRAD CHATBOT ASSISTANT
   ------------------------------------------------------------
   Rule-based FAQ helper.
   No API calls.
   No localStorage.
   No sessionStorage.
   No cookies.
   No database storage.

   The chat history exists only in this browser page's memory.
   ============================================================ */

(function() {

  /*
   * These values are generated by PHP and injected into the
   * page through the global TRACEGRAD_STATS object.
   *
   * In your index.php, place this BEFORE loading script.js:
   *
   * <script>
   * const TRACEGRAD_STATS = {
   *   totalAlumni: <?= (int) $totalAlumni ?>,
   *   totalColleges: <?= (int) $totalColleges ?>,
   *   totalCourses: <?= (int) $totalCourses ?>,
   *   surveyPct: <?= (int) $surveyPct ?>,
   *   employedPct: <?= (int) $employedPct ?>
   * };
   * </script>
   */

  const SITE_STATS = window.TRACEGRAD_STATS || {
    totalAlumni: 0,
    totalColleges: 0,
    totalCourses: 0,
    surveyPct: 0,
    employedPct: 0
  };


  /* ==========================================================
     CHAT MEMORY
     ========================================================== */

  let chatHistory = [];
  let hasGreeted = false;


  /* ==========================================================
     CHAT INTENTS
     ========================================================== */

  const INTENTS = [

    /* ---------------- GREETING ---------------- */

    {
      name: 'greeting',

      patterns: [
        'hi',
        'hello',
        'hey',
        'good morning',
        'good afternoon',
        'good evening',
        'kumusta',
        'kamusta'
      ],

      response: function() {
        return `Hi there! 👋 I'm the TRACEGRAD Assistant. I can help with signing in, account activation, the CHED survey, or the photo gallery. What do you need?`;
      }
    },


    /* ---------------- SIGN IN ---------------- */

    {
      name: 'signin_help',

      patterns: [
        'sign in',
        'signin',
        'log in',
        'login',
        'how do i login',
        'how to login',
        'access my account'
      ],

      response: function() {
        return `To sign in: go to "Alumni Sign In," enter your Student Number and password. If you don't have a password yet, the system will send you straight to account activation instead.`;
      }
    },


    /* ---------------- ACCOUNT ACTIVATION ---------------- */

    {
      name: 'activation_help',

      patterns: [
        'activate',
        'activation',
        'new account',
        'first time',
        'create account',
        'set up account',
        'setup account'
      ],

      response: function() {
        return `Account activation is one-time: enter your Student Number, confirm your last name and registered email (student or personal), then set a password. This proves you're the graduate on record before we let you in.`;
      }
    },


    /* ---------------- FORGOT PASSWORD ---------------- */

    {
      name: 'forgot_password',

      patterns: [
        'forgot password',
        'forgot my password',
        'reset password',
        "can't remember",
        'cant remember',
        'lost password'
      ],

      response: function() {
        return `I can't reset passwords from here for security reasons — please contact your College/Department Admin or the Alumni Affairs Office with your Student Number, and they'll issue you a new one.`;
      }
    },


    /* ---------------- ADMIN LOGIN ---------------- */

    {
      name: 'admin_login',

      patterns: [
        'admin login',
        'administrator',
        'admin portal',
        'admin sign in'
      ],

      response: function() {
        return `Administrators use the separate "Admin Login" button in the top navigation — that's for Super Admins and College/Department Admins only, not alumni accounts.`;
      }
    },


    /* ---------------- CHED SURVEY ---------------- */

    {
      name: 'survey',

      patterns: [
        'survey',
        'tracer survey',
        'ched',
        'tracer study'
      ],

      response: function() {
        return `The CHED Graduate Tracer Survey helps ISUFST measure how well its programs prepare graduates for the workforce. Right now about ${SITE_STATS.surveyPct}% of alumni on record have completed it. You can take it once, from the Survey tab in your alumni dashboard.`;
      }
    },


    /* ---------------- PHOTO GALLERY ---------------- */

    {
      name: 'gallery',

      patterns: [
        'gallery',
        'photo',
        'picture',
        'pictures',
        'download hd',
        'price',
        'gcash',
        'buy photo'
      ],

      response: function() {
        return `Free low-resolution previews are open to everyone on the Photo Gallery page. To download a full HD, watermark-free original, sign in to your alumni account, pay the listed price via GCash, and submit your reference number — the Alumni Affairs Office verifies it before the HD unlocks.`;
      }
    },


    /* ---------------- COLLEGES / PROGRAMS ---------------- */

    {
      name: 'colleges',

      patterns: [
        'college',
        'program',
        'course',
        'department',
        'degree'
      ],

      response: function() {
        return `ISUFST San Enrique currently has ${SITE_STATS.totalColleges} active college(s) offering ${SITE_STATS.totalCourses} degree program(s). Check the "About" tab above for the full list with course codes.`;
      }
    },


    /* ---------------- EMPLOYMENT ---------------- */

    {
      name: 'employment',

      patterns: [
        'employment',
        'employed',
        'job stats',
        'employment rate',
        'job rate'
      ],

      response: function() {
        return `Based on current tracer data, about ${SITE_STATS.employedPct}% of alumni on record are employed, self-employed, or freelancing. These figures update as more alumni complete their profile and survey.`;
      }
    },


    /* ---------------- CONTACT / SUPPORT ---------------- */

    {
      name: 'contact',

      patterns: [
        'contact',
        'support',
        'office',
        'email',
        'phone',
        'help',
        'human',
        'real person'
      ],

      response: function() {
        return `For anything I can't resolve, reach the ISUFST Alumni Affairs Office directly, or your College/Department Admin for roster and account-specific concerns.`;
      }
    },


    /* ---------------- THANKS ---------------- */

    {
      name: 'thanks',

      patterns: [
        'thank',
        'thanks',
        'salamat',
        'appreciate it'
      ],

      response: function() {
        return `You're welcome! Let me know if anything else comes up.`;
      }
    },


    /* ---------------- GOODBYE ---------------- */

    {
      name: 'bye',

      patterns: [
        'bye',
        'goodbye',
        'see you',
        'good night'
      ],

      response: function() {
        return `Take care! Come back anytime you have a question about your alumni account.`;
      }
    }

  ];


  /* ==========================================================
     FALLBACK RESPONSE
     ========================================================== */

  const FALLBACK = function() {
    return `I'm not sure about that one yet — I only handle common questions about signing in, account activation, the CHED survey, and the photo gallery. For anything else, please contact the ISUFST Alumni Affairs Office or your College/Department Admin.`;
  };


  /* ==========================================================
     MATCH USER MESSAGE TO INTENT
     ========================================================== */

  function matchIntent(raw) {

    const text = raw.toLowerCase();

    for (const intent of INTENTS) {

      if (
        intent.patterns.some(function(pattern) {
          return text.includes(pattern);
        })
      ) {
        return intent;
      }

    }

    return null;
  }


  /* ==========================================================
     MESSAGE TIME
     ========================================================== */

  function nowLabel() {

    return new Date().toLocaleTimeString([], {
      hour: '2-digit',
      minute: '2-digit'
    });

  }


  /* ==========================================================
     ESCAPE HTML
     ========================================================== */

  function escapeHTML(text) {

    const div = document.createElement('div');

    div.textContent = text;

    return div.innerHTML;
  }


  /* ==========================================================
     RENDER CHAT MESSAGE
     ========================================================== */

  function renderMessage(role, text) {

    const wrap = document.getElementById('chat-msgs');

    if (!wrap) return;

    const row = document.createElement('div');

    row.className = 'chat-msg ' + role;

    const safeText = escapeHTML(text);

    row.innerHTML =
      (role === 'bot'
        ? '<div class="chat-msg-av">TG</div>'
        : '') +

      '<div class="chat-bubble">' +
        safeText +
        '<span class="chat-msg-time">' +
          nowLabel() +
        '</span>' +
      '</div>';

    wrap.appendChild(row);

    wrap.scrollTop = wrap.scrollHeight;
  }


  /* ==========================================================
     SHOW TYPING INDICATOR
     ========================================================== */

  function showTyping() {

    const wrap = document.getElementById('chat-msgs');

    if (!wrap) return;

    const row = document.createElement('div');

    row.className = 'chat-msg bot';

    row.id = 'chat-typing-row';

    row.innerHTML =
      '<div class="chat-msg-av">TG</div>' +
      '<div class="chat-typing">' +
        '<span></span>' +
        '<span></span>' +
        '<span></span>' +
      '</div>';

    wrap.appendChild(row);

    wrap.scrollTop = wrap.scrollHeight;
  }


  /* ==========================================================
     HIDE TYPING INDICATOR
     ========================================================== */

  function hideTyping() {

    const row =
      document.getElementById('chat-typing-row');

    if (row) {
      row.remove();
    }
  }


  /* ==========================================================
     BOT RESPONSE
     ========================================================== */

  function respondTo(userText) {

    showTyping();

    window.setTimeout(function() {

      hideTyping();

      const intent = matchIntent(userText);

      const reply =
        intent
          ? intent.response()
          : FALLBACK();

      chatHistory.push({
        role: 'bot',
        text: reply,
        intent: intent
          ? intent.name
          : 'fallback'
      });

      renderMessage(
        'bot',
        reply
      );

    }, 500 + Math.random() * 400);
  }


  /* ==========================================================
     SEND CHAT MESSAGE
     ========================================================== */

  window.sendChat = function() {

    const input =
      document.getElementById('chat-input');

    if (!input) return;

    const text =
      input.value.trim();

    if (!text) return;

    chatHistory.push({
      role: 'user',
      text: text
    });

    renderMessage(
      'user',
      text
    );

    input.value = '';

    respondTo(text);
  };


  /* ==========================================================
     QUICK CHAT BUTTON
     ========================================================== */

  window.sendQuick = function(text) {

    const box =
      document.getElementById('chatbot-box');

    if (box) {
      box.classList.add('open');
    }

    chatHistory.push({
      role: 'user',
      text: text
    });

    renderMessage(
      'user',
      text
    );

    respondTo(text);
  };


  /* ==========================================================
     TOGGLE CHATBOT
     ========================================================== */

  window.toggleChatbot = function(force) {

    const box =
      document.getElementById('chatbot-box');

    if (!box) return;

    const open =
      typeof force === 'boolean'
        ? force
        : !box.classList.contains('open');

    box.classList.toggle(
      'open',
      open
    );

    /*
     * Greet the visitor only the first time
     * the chatbot is opened.
     */
    if (open && !hasGreeted) {

      hasGreeted = true;

      respondTo('hello');
    }

    if (open) {

      const input =
        document.getElementById('chat-input');

      if (input) {
        input.focus();
      }
    }
  };

})();